In [1]:
import numpy as np

In [2]:
# creating the base lists
list1 = []

In [3]:
# user creates list1
for i in range(4):
  list1.append(int(input("Digite um número para a primeira matriz: ")))


Digite um número para a primeira matriz: 6
Digite um número para a primeira matriz: 2
Digite um número para a primeira matriz: 1
Digite um número para a primeira matriz: 0


In [4]:
# generating list2
list2 = list(map(lambda n: n + 1, list1))
print(list2)

[7, 3, 2, 1]


In [5]:
# manipulating the lists and create an array numpy of 4 dimensions with funcions
arr_4d = np.array([
    [
        [
            list((map(lambda n: n * 1, list1))),
            list((map(lambda n: n * 2, list1))),
            list((map(lambda n: n * 3, list1))),
            list((map(lambda n: n * 4, list1)))
        ],
        [
            list((map(lambda n: n + 2, list1))),
            list((map(lambda n: n + 4, list1))),
            list((map(lambda n: n + 6, list1))),
            list((map(lambda n: n + 8, list1)))
        ]
    ],
    [
        [
            list((map(lambda n: n * 1, list2))),
            list((map(lambda n: n * 5, list2))),
            list((map(lambda n: n * 10, list2))),
            list((map(lambda n: n * 15, list2)))
        ],
        [
            list((map(lambda n: n + 10, list2))),
            list((map(lambda n: n + 12, list2))),
            list((map(lambda n: n + 14, list2))),
            list((map(lambda n: n + 16, list2)))
        ]
    ]
])

In [6]:
print(arr_4d)

[[[[  6   2   1   0]
   [ 12   4   2   0]
   [ 18   6   3   0]
   [ 24   8   4   0]]

  [[  8   4   3   2]
   [ 10   6   5   4]
   [ 12   8   7   6]
   [ 14  10   9   8]]]


 [[[  7   3   2   1]
   [ 35  15  10   5]
   [ 70  30  20  10]
   [105  45  30  15]]

  [[ 17  13  12  11]
   [ 19  15  14  13]
   [ 21  17  16  15]
   [ 23  19  18  17]]]]
