In [1]:
import numpy as np

In [32]:
# creating the base lists
mut3 = [0,3,6,9]
mut4 = [0,4,8,12]

# manipulating the lists and create an array numpy of 4 dimensions with funcions
arr_4d = np.array([
    [
        [list((map(lambda n: n * 1, mut3)))],
        [list((map(lambda n: n * 2, mut3)))],
        [list((map(lambda n: n * 3, mut3)))],
        [list((map(lambda n: n * 4, mut3)))]
    ],
    [
        [list((map(lambda n: n * 1, mut4)))],
        [list((map(lambda n: n * 2, mut4)))],
        [list((map(lambda n: n * 3, mut4)))],
        [list((map(lambda n: n * 4, mut4)))]
    ]
])

In [30]:
arr_4d.shape

(2, 4, 1, 4)

In [33]:
arr_4d.ndim

4

In [31]:
print(arr_4d)

[[[[ 0  3  6  9]]

  [[ 0  6 12 18]]

  [[ 0  9 18 27]]

  [[ 0 12 24 36]]]


 [[[ 0  4  8 12]]

  [[ 0  8 16 24]]

  [[ 0 12 24 36]]

  [[ 0 16 32 48]]]]


In [38]:
arr_4d[0,3,0,3] + arr_4d[1,3,0,3]

84